version: '3'

volumes:
  bundle:
  elastic:

services:
  db:
    image: postgres:11.6
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  web: &rails
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    depends_on:
      - db
      - redis
      - elasticsearch
    tmpfs: /app/tmp
    ports:
      - "3000:3000"
    env_file: app.env
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_REQUEST_TIMEOUT=300 #seconds
      - ELASTIC_USER=elastic
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - ELASTIC_COMPRESSION=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    tty: true
    stdin_open: true

  sidekiq:
    <<: *rails
    command: bundle exec sidekiq -C config/sidekiq.yml
    ports: []

  redis:
    container_name: redis
    image: redis

  elasticsearch:
    image: elasticsearch:7.4.1
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=true
    volumes:
      - elastic:/usr/share/elasticsearch/data
    healthcheck:
      test: curl -s http://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - 9200:9200

  ngrok:
    image: wernight/ngrok
    ports:
      - 4040:4040
    environment:
      NGROK_PORT: 'web:3000'
