version: '3'

volumes:
  db:
  bundle:
  elastic:

services:
  db:
    image: postgres:12.0
    volumes:
      - db:/var/lib/postgresql/data

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - app

  app: &rails
    image: ilabsea/event_base_surveillance:0.1
    restart: unless-stopped
    volumes:
      - bundle:/usr/local/bundle
    depends_on:
      - db
      - redis
      - elasticsearch
    environment:
      - LANG=C.UTF-8
      - DATABASE_URL=postgres://postgres@db/ebs_production
      - RAILS_SERVE_STATIC_FILES=true
      - REDIS_URL=redis://redis:6379
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_REQUEST_TIMEOUT=300 #seconds
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=elastic
      - ELASTIC_COMPRESSION=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - SETTINGS__SMTP__ADDRESS=smtp.mandrillapp.com
      - SETTINGS__SMTP__DOMAIN=domain
      - SETTINGS__SMTP__USER_NAME=email
      - SETTINGS__SMTP__PASSWORD=api-key
      - SETTINGS__SMTP__HOST=localhost:3000
      - SETTINGS__SMTP__DEFAULT_FROM=notifications@example.com
      - TELEGRAM_TOKEN=your_token
      - TELEGRAM_USERNAME=your_bot_name
      - ENABLE_EVENT_WORKER=true
      - VIRTUAL_HOST=example.com
      - VIRTUAL_PORT=80
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '5'
    command:
    - /bin/sh
    - -c
    - bundle exec puma -e production -b tcp://0.0.0.0:80

  sidekiq:
    <<: *rails
    command: bundle exec sidekiq -C config/sidekiq.yml
    ports: []

  redis:
    image: redis:5.0.6

  elasticsearch:
    image: elasticsearch:7.4.1
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=elastic
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=true
    volumes:
      - elastic:/usr/share/elasticsearch/data
    healthcheck:
      test: curl -s http://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5
