---
:concurrency: 5
staging:
  :concurrency: 10
production:
  :concurrency: 20
:queues:
  - ["mailers", 2]
  - ["default", 2]
  - ["indexers", 1]

:max_retries: 15

:schedule:
  lockevent:
    # at At 00:00.
    cron: "0 0 * * *"
    class: LockEventJob

  process_feed:
    # every one hour
    cron: "0 * * * *"
    class: MedisyWorker

  schedule_follow_up:
    # every one hour
    cron: "0 * * * *"
    class: ScheduleWorker

  pull_mbds_outbreak_report:
    # At every 5th minute.
    cron: "*/5 * * * *"
    class: MbdsOutbreakReportWorker
